
version: '3.8' # Specify the Docker Compose file format version



services:

  # Service for your backend application

  backend:

    build: ./backend # Build the image from the Dockerfile in the ./backend directory

    container_name: scuba-ai-backend-container # Assign a specific name to the container

    ports:

      - "5000:5000" # Map port 5000 on the host to port 5000 in the container

    environment:

      # Load environment variables from the .env file

      # The GROQ_API_KEY will be loaded from here

      - GROQ_API_KEY=${GROQ_API_KEY}

    env_file:

      - .env # Specify the .env file to load environment variables from

    restart: always # Automatically restart the container if it stops

